WITH CNT_DEPT AS
(
SELECT DEPARTMENT_ID,
 COUNT(1) NUM_EMP
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
)
SELECT EMPLOYEE_ID,
 SALARY/NUM_EMP
FROM EMPLOYEES E,
 CNT_DEPT C
WHERE E.DEPARTMENT_ID = C.DEPARTMENT_ID;