SELECT *FROM SYS.ALL_DEPENDENCIES WHERE ROWNUM < 10
/

ALTER USER hr ACCOUNT UNLOCK;

ALTER USER hr IDENTIFIED BY hr;


GRANT EXECUTE ON utl_file TO PUBLIC;
CREATE OR REPLACE PUBLIC SYNONYM utl_file FOR sys.utl_file;


Select *from user_source ---where name=’PROCEDURE_NAME’;
